version: "3.9"
services:
  discovery:
    build: Atelier2
    ports:
      - "8761"
    image: "discovery-service"

  candidat:
    build: Atelier1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "3000:8083"
    image: "candidate-service"
    depends_on:
      - job_A

  job_A:
    build: GestionJob
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8082"
    image: "job-service"
